name 'formatron_filebeat'
version '0.1.1'
description 'Formatron Filebeat cookbook'
maintainer 'Peter Halliday'
maintainer_email 'pghalliday@gmail.com'
source_url 'https://github.com/formatron/filebeat-cookbook'
issues_url 'https://github.com/formatron/filebeat-cookbook/issues'
supports 'ubuntu'
depends 'formatron_beats'
